### ISSUE TITLE
TotalSize dans KServer.cs

### ISSUE THREAD

**Issue by crashyear** [KankuruSQL/KMO#3]
Bonjour,
Il y a une petite erreur à partir de la ligne 1313, la colonne TotalSize est parfois utilisée en "totalsize" et pour certaines instances sur le dashboard la requete sur l'utilisation disque ne fonctionne pas avec le message "InvalidColumName"
J'ai corrigé le fichier et tu le trouveras en PJ :
[KServer.cs.txt](https://github.com/KankuruSQL/KMO/files/3127308/KServer.cs.txt)

**Comment by gboge** [comment]
Bonjour,
J'ai effectué le changement. Ce sera disponible dans peu de temps dans la version 1.4.7
